### ISSUE TITLE
Merchant Signature

### ISSUE THREAD

**Issue by CrackerakiUA** [fducom/wayforpay#2]
Is there a way to pull merchant signature from this package?
Lets say that we want to use https://wiki.wayforpay.com/pages/viewpage.action?pageId=852091 this widget inside our app. This modal require to have merchantSignature which I understood that we need to connect with an REST API to get it, this one https://wiki.wayforpay.com/pages/viewpage.action?pageId=1736983
Am I on the right path? This package can help, or we need to improve it?

**Comment by fducom** [comment]
Yes, sorry for long delay answer(
